name: mesh-simplification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - rtree
  - pip:
      # Benchmark pipeline
      - pyvista
      - fast-simplification
      - open3d
      - meshoptimizer
      - trimesh
      - psutil
      # Analysis
      - numpy
      - scipy
      - pandas
      - matplotlib
      - seaborn
      - tqdm
      # Perceptual study
      - flask